<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="abstracta" nsURI="abstracta" nsPrefix="abstracta">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModelFactoryAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaPaquetes" upperBound="-1"
        eType="#//PaqueteAbstracta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaqueteAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaClases" upperBound="-1"
        eType="#//ClaseAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaPaquetes" upperBound="-1"
        eType="#//PaqueteAbstracta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClaseAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAtributos" upperBound="-1"
        eType="#//AtributoAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaMetodos" upperBound="-1"
        eType="#//MetodoAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaRelaciones" upperBound="-1"
        eType="#//RelacionAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaRelacionesHerencia"
        upperBound="-1" eType="#//HerenciaAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaRelacionesContaiment"
        upperBound="-1" eType="#//ContainmentAbstracta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtributoAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParametroAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MetodoAbstracta">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nombre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sentencias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valorRetorno" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaParametros" upperBound="-1"
        eType="#//ParametroAbstracta" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listaAtributos" upperBound="-1"
        eType="#//AtributoAbstracta" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelacionAbstracta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ClaseAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClaseAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentAbstracta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ClaseAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClaseAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicidadB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rolB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HerenciaAbstracta">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//ClaseAbstracta"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//ClaseAbstracta"/>
  </eClassifiers>
</ecore:EPackage>
